### PR TITLE
Blogit: - Feature/controller specs 👨🏾‍💻 🧭 💻 🧪 

### PR DESCRIPTION
**Pull request by Bennyjoez**
## Blogit: - Feature/controller specs 👨🏾‍💻 🧭 💻 🧪 

In this milestone, I managed to do the following: 🪶 
- Add RSpec as a gem to the project. 📄 
- Create a Request spec file for all controllers. 🎛️ 
- Made sure that for each action I checked:
   -  If the response status was correct. ✔️ 
   -  If a correct template was rendered. ✔️ 
   -  If the response body includes correct placeholder text. ✔️ 

💯

### CODE REVIEW

**Review by TadesseDev — CHANGES_REQUESTED** [review]
### Hi @Bennyjoez 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑🛑
yPkfDFf

- [ ] Please consider removing the `Live demo` section from the readme file. It is only required when you have a project that is deployed. If not, the section is expected to be removed. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Bennyjoez** [comment]
@TadesseDev I have just specified there it's not live yet. This speaks about plans to make it live in the near future. Is it not enough?

**Comment by TadesseDev** [comment]
Dear @Bennyjoez, I'm following the review guideline here, and according to it, if the project is not deployed yet, the live demo section should be removed.

**Comment by Bennyjoez** [comment]
Changes effected

**Review by OLIPLICHE — APPROVED** [review]
Hi @Bennyjoez, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights
- Add Rspec as gem (✅)) 👏
- Written the test for controllers👏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
